### ISSUE TITLE
Tool defaults to currently installed Drive

### ISSUE THREAD

**Issue by zoeyronain** [corpnewt/Mac-Multi-Tool#1]
Just ran this to create an installer, and it defaulted to my SSD. It tried erasing it but couldn't unmount /. Can you make it smart enough to ignore the current boot device?

**Comment by corpnewt** [comment]
Umm... Probably not for the next few days or so - why are you just pressing
enter through the prompts though?

**Comment by zoeyronain** [comment]
because I was in a hurry and didn't expect it to auto select something at the choose a volume :P

**Comment by corpnewt** [comment]
I mean - I'll look at it when I have time, but I think you're the first
person to do that haha. But no matter what - it can't unmount and erase the
boot drive so that may be better than having a different default or
something.
